name: Build and Deploy Server/Studio

on:
  workflow_call:
    inputs:
      NODE_ENV:
        # `debug` or `release`
        type: string
        required: true
      deploy:
        type: boolean
        required: true
    secrets:
      publishProfile:
        # must be set if `deploy` is `true`
        required: false
        description: 'App Service secret'
      STATIC_WEB_APPS_TOKEN:
        # must be set if `deploy` is `true`
        required: false
      DATABASE_USERNAME:
        required: true
      DATABASE_PASSWORD:
        required: true

jobs:
  build-server:
    name: Build Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # required for webpack
      - name: Create .env file
        run: |
          touch ./projects/server/.env
          echo NODE_ENV=${{ inputs.NODE_ENV }} >> ./projects/server/.env
          echo IS_LOCAL=false >> ./projects/server/.env
          echo "NAME=\"${{ github.sha }} - ${{ github.event_name }} - ${{ github.head_ref || github.ref_name }}\"" >> ./projects/server/.env
          cat ./projects/server/.env

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install node modules
        run: yarn install

      - name: Build typescript project
        run: yarn workspace server build:${{ inputs.NODE_ENV }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: built-server-files
          path: ./dist/**
  
  test-server:
    name: Test Server
    runs-on: ubuntu-latest

    steps:
      # note: we don't use the built artifact because `ts-jest` builds TS files on the fly
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create test.env file
        # we are using separate test tables for the develop/master tests so they can run in parallel if needed
        run: |
          touch ./projects/server/test.env
          echo "DATABASE_URL=\"mysql://${{ secrets.DATABASE_USERNAME }}:${{ secrets.DATABASE_PASSWORD }}@chat-mate.mysql.database.azure.com:3306/chat_mate_test${{ inputs.NODE_ENV == 'debug' && '_debug' || '' }}?connection_limit=5&pool_timeout=30&connect_timeout=30\"" >> ./projects/server/test.env
          cat ./projects/server/test.env

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install node modules
        run: yarn install

      - name: Set up test database
        run: yarn workspace server test:db
          
      - name: Generate Prisma client
        run: yarn workspace server generate

      - name: Run tests
        timeout-minutes: 10
        run: yarn workspace server test

  build-studio:
    name: Build Studio
    runs-on: ubuntu-latest
    needs: build-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Download built server files
        uses: actions/download-artifact@v2
        with:
          name: built-server-files
          path: ./dist/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install node modules
        run: yarn install
      
      - name: Build typescript project
        run: yarn workspace studio build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: built-studio-files
          path: ./projects/studio/build/**

  deploy-server:
    if: inputs.deploy == true
    name: Deploy Server
    runs-on: ubuntu-latest
    needs: [build-server, test-server, build-studio]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download built server files
        uses: actions/download-artifact@v2
        with:
          name: built-server-files

      - name: Deploy to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.NODE_ENV == 'debug' && 'chat-mate-sandbox' || 'chat-mate-prod' }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.publishProfile }}
          package: .

  deploy-studio:
    if: inputs.deploy == true
    name: Deploy Studio
    runs-on: ubuntu-latest
    needs: [build-server, test-server, build-studio]

    steps:
      - name: Download built studio files
        uses: actions/download-artifact@v2
        with:
          name: built-studio-files

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # see https://docs.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions
          azure_static_web_apps_api_token: ${{ secrets.STATIC_WEB_APPS_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (e.g. PR comments)
          action: upload
          skip_app_build: true
          app_location: .
