name: Deploy Server/Studio

on:
  workflow_call:
    secrets:
      publishProfile:
        required: true
        description: 'App Service secret'

jobs: 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: Built files

      - name: Deploy to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'chat-mate-prod'
          slot-name: 'Production'
          publish-profile: ${{ secrets.publishProfile }}
          package: .
