name: Sandbox

on:
  push:
    branches-ignore:
      - 'master'
  pull_request:
    types: [opened]
    branches:
      - develop
  workflow_dispatch:

jobs:  
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      NODE_ENV: 'debug'
      deploy: ${{ github.event.github.ref_name == 'develop' }}
    secrets:
      publishProfile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9BBD3D4C46274FCD94006579EB592F31 }}
      STATIC_WEB_APPS_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_COAST_05A39C31E }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
