name: Sandbox

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened]
    branches:
      - develop
  workflow_dispatch:

jobs:  
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      NODE_ENV: 'debug'
      deploy: true
    secrets:
      publishProfile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9BBD3D4C46274FCD94006579EB592F31 }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
